DROP TABLE IF EXISTS user;

CREATE TABLE user
(
	id BIGINT(20) NOT NULL COMMENT '主键ID',
	user_name VARCHAR(50) NULL DEFAULT NULL COMMENT '姓名',
	password VARCHAR(50) NULL DEFAULT NULL COMMENT '密码',
    roles VARCHAR(50) NULL DEFAULT NULL COMMENT '权限',
	PRIMARY KEY (id)
);
